2024-06-20 08:57:52.671888
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-06-21 08:44:33.438881
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-06-22 08:44:13.247577
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-06-23 08:49:19.606002
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-06-24 08:46:55.725309
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-06-25 08:45:11.775675
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-06-26 08:45:11.145097
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-06-27 08:45:37.148785
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-06-28 08:45:30.136474
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-06-29 08:44:22.494853
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-06-30 08:51:01.099497
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-01 08:52:48.219578
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-02 08:45:57.442422
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-03 08:45:40.861966
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-04 08:46:05.422567
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-05 08:45:22.901375
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-06 08:44:21.354015
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-07 08:51:27.710676
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-08 08:48:05.051363
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-09 08:46:32.030520
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-10 08:47:04.445079
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-11 08:47:18.423254
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-12 08:46:13.091383
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-13 08:47:15.725243
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-14 08:52:07.656737
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-15 08:49:30.325312
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-16 08:47:47.613486
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-17 08:47:47.810756
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-18 08:46:19.701201
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-19 11:19:37.042795
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-20 08:46:01.913052
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-21 08:52:05.033778
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-22 08:50:00.647888
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-23 08:47:52.204363
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-24 08:48:37.206760
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-25 08:47:24.518803
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-26 08:46:59.502980
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-27 08:46:41.837593
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-28 08:52:16.653942
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-29 08:49:42.976465
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-30 08:47:44.267443
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-31 08:39:09.075155
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-01 08:53:07.724746
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-02 08:47:53.759416
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-03 08:46:53.979767
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-04 08:52:42.847702
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-05 08:50:23.713590
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-06 08:48:06.054458
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-07 08:49:09.387992
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-08 08:48:41.042383
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-09 08:49:47.850654
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-10 08:48:49.339796
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-11 08:53:14.324812
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-12 08:50:51.221265
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-13 08:50:32.879186
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-14 08:49:11.943422
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-15 08:46:21.424328
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-16 08:48:20.014860
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-17 08:46:31.103357
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-18 08:52:30.514152
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-19 08:50:07.577732
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-20 08:48:31.186735
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-21 08:48:24.632396
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-22 08:50:30.271526
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-23 08:48:57.292616
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-24 08:47:27.099253
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-25 08:53:48.319701
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-26 08:50:06.368314
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-27 08:50:38.752646
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-28 08:50:53.912641
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-29 08:51:14.077551
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-30 08:51:44.725683
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-31 08:51:09.562040
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-01 08:59:57.934839
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-02 08:52:48.345127
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-03 08:50:59.814435
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-04 08:51:51.515057
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-05 08:51:47.009681
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-06 08:51:34.478678
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-07 08:51:01.839646
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-08 08:56:16.290278
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-09 08:53:55.760754
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-10 08:52:33.491087
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-11 08:52:10.549081
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-12 08:52:21.536396
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-13 08:52:21.897417
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-14 08:51:42.710404
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-15 08:58:06.995814
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-16 08:55:42.836425
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-17 08:42:34.546854
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-18 08:52:31.924062
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-19 08:53:09.231674
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-20 08:53:10.934073
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-21 08:52:24.731810
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-22 08:58:21.154674
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-23 08:54:49.878036
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-24 08:55:11.109101
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-25 08:55:24.612729
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-26 08:54:25.786803
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-27 08:54:28.220563
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-28 08:54:12.351365
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-29 08:59:06.399203
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-09-30 08:56:42.391380
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-10-01 09:00:04.408928
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-10-02 08:54:43.484465
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-10-03 08:54:37.403103
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-10-04 08:54:42.840302
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-10-05 08:54:04.128136
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-10-06 08:58:51.365653
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-10-07 08:56:45.072817
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-10-08 08:54:40.894503
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-10-09 08:54:25.645770
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-10-10 08:54:34.441401
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-10-11 08:54:34.810942
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-10-12 08:53:28.486970
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-10-13 08:58:33.612679
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-10-14 08:56:32.788425
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-10-15 08:55:32.648741
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-10-16 08:55:35.522116
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-10-17 08:54:51.840105
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-10-18 08:54:58.842585
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-10-19 08:54:36.818024
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-10-20 08:59:43.399569
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

