2023-07-06 08:59:57.504207
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-07-08 08:58:14.485244
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-07-09 09:02:13.023131
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-07-10 08:58:23.218663
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 624, in get_pickup
    img_urls = img_soup.get("srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 626, in get_pickup
    img_urls = img_soup.get("data-srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

