2024-06-20 08:57:52.671888
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-06-21 08:44:33.438881
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-06-22 08:44:13.247577
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-06-23 08:49:19.606002
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-06-24 08:46:55.725309
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-06-25 08:45:11.775675
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-06-26 08:45:11.145097
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-06-27 08:45:37.148785
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-06-28 08:45:30.136474
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-06-29 08:44:22.494853
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-06-30 08:51:01.099497
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-01 08:52:48.219578
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-02 08:45:57.442422
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-03 08:45:40.861966
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-04 08:46:05.422567
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-05 08:45:22.901375
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-06 08:44:21.354015
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-07 08:51:27.710676
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-08 08:48:05.051363
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-09 08:46:32.030520
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-10 08:47:04.445079
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-11 08:47:18.423254
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-12 08:46:13.091383
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-13 08:47:15.725243
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-14 08:52:07.656737
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-15 08:49:30.325312
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-16 08:47:47.613486
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-17 08:47:47.810756
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-18 08:46:19.701201
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-19 11:19:37.042795
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-20 08:46:01.913052
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-21 08:52:05.033778
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-22 08:50:00.647888
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-23 08:47:52.204363
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-24 08:48:37.206760
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-25 08:47:24.518803
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-26 08:46:59.502980
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-27 08:46:41.837593
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-28 08:52:16.653942
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-29 08:49:42.976465
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-30 08:47:44.267443
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-07-31 08:39:09.075155
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-01 08:53:07.724746
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-02 08:47:53.759416
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-03 08:46:53.979767
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-04 08:52:42.847702
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-05 08:50:23.713590
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-06 08:48:06.054458
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-07 08:49:09.387992
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-08 08:48:41.042383
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-09 08:49:47.850654
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-10 08:48:49.339796
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-11 08:53:14.324812
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-12 08:50:51.221265
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-13 08:50:32.879186
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-14 08:49:11.943422
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-15 08:46:21.424328
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-16 08:48:20.014860
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-17 08:46:31.103357
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-18 08:52:30.514152
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-19 08:50:07.577732
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-20 08:48:31.186735
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-21 08:48:24.632396
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-22 08:50:30.271526
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

2024-08-23 08:48:57.292616
maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 29, in <module>
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 100, in down_all_card_res
    down_all_card_res()
  [Previous line repeated 991 more times]
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 97, in down_all_card_res
    download_svt()
  File "/home/runner/work/fgo_data/fgo_data/download/download_all_res.py", line 17, in download_svt
    svt = json.load(f)
          ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

